sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
after_success:
- ./node_modules/.bin/jscoverage generators generators-cov --exclude templates
- ./node_modules/.bin/mocha ./test/test-app.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js