sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
after_success:
- ./node_modules/.bin/mocha ./test/test-app.js -R mocha-lcov-reporter > coverage_temp.lcov
- sed 's,25h,,' coverage_temp.lcov > coverage.lcob 
- cat coverage.lcov | ./node_modules/coveralls/bin/coveralls.js