sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
- ./node_modules/.bin/jscoverage generators generators-cov --exclude templates
after_success:
- ./node_modules/.bin/mocha ./test/test-app.js -R mocha-lcov-reporter > coverage.lcov
- cat coverage.lcov
- cat coverage.lcov | node ./node_modules/coveralls/bin/coveralls.js