sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
after_success:
- ./node_modules/.bin/mocha ./test/test-app.js -R mocha-lcov-reporter > coverage_temp.lcov
- cat coverage_temp.lcov | %{$_ -replace "25h",""} | ./node_modules/coveralls/bin/coveralls.js